/**
 * 
 * @author Geppetto Generated Code</br>
 * Date Created: </br>
 * @since  </br>
   build:   </p> 
 *
 * code was generated by the Geppetto System </br>
 * Gepppetto system Copyright - Geppetto LLC </br>
 * The generated code is free to use by anyone</p>
 *
 *
 *
*/

DROP DATABASE IF EXISTS geppetto_braintree;

CREATE DATABASE geppetto_braintree
CHARACTER SET utf8mb4
COLLATE utf8mb4_bin