/**
 * 
 * @author Geppetto Generated Code</br>
 * Date Created: </br>
 * @since  </br>
   build:   </p> 
 *
 * code was generated by the Geppetto System </br>
 * Gepppetto system Copyright - Geppetto LLC </br>
 * The generated code is free to use by anyone</p>
 *
 *
 *
*/


CREATE TABLE geppetto_braintree.customer (
	id int(10) NOT NULL,
	first_name varchar(250),
	last_name varchar(250),
	company varchar(250),
	email varchar(250),
	phone varchar(250),
	fax varchar(250),
	website varchar(250),
	number_of_payment_methods int(10),
	number_of_transactions int(10),
	created_date date,
	last_updated_date date,
	PRIMARY KEY (id)
) ENGINE=InnoDB;
CREATE TABLE geppetto_braintree.`order` (
	id int(10) NOT NULL,
	customer_id int(10),
	product_id int(10),
	order_date TIMESTAMP,
	PRIMARY KEY (id)
) ENGINE=InnoDB;
CREATE TABLE geppetto_braintree.order_detail (
	id int(10) NOT NULL,
	order_id int(10),
	product_id int(10),
	quantity int(10),
	PRIMARY KEY (id)
) ENGINE=InnoDB;
CREATE TABLE geppetto_braintree.product (
	id int(10) NOT NULL,
	name varchar(250),
	description varchar(250),
	price double,
	image varchar(250),
	PRIMARY KEY (id)
) ENGINE=InnoDB;
CREATE TABLE geppetto_braintree.subscription (
	id int(10) NOT NULL,
	customer_id int(10),
	payment_method_token varchar(50),
	plan_id varchar(50),
	plan_name varchar(250),
	status_merchant_account varchar(50),
	descriptor_name varchar(250),
	descriptor_phone varchar(50),
	descriptor_url varchar(250),
	subscription_price double,
	subscription_currency varchar(50),
	trial_period varchar(250),
	first_bill_date date,
	current_billing_period varchar(250),
	paid_through_date varchar(250),
	next_bill_date date,
	balance double,
	currency varchar(250),
	next_billing_period_amount varchar(250),
	number_of_transaccions int(10),
	number_of_addons int(10),
	number_of_discounts int(10),
	number_of_billing_cycles int(10),
	PRIMARY KEY (id)
) ENGINE=InnoDB;
INSERT INTO geppetto_braintree.customer(id, first_name, last_name, company, email, phone, fax, website, number_of_payment_methods, number_of_transaccions, created_date, last_updated_date) VALUES (1, 'Reinaldo', 'Lopez', 'geppetto', 'lopezreinaldoernesto@gmail.com', '023439439', '90434920', '', 0, 0, '2015-09-22', '2015-09-22');
