package com.geppetto.braintree.controller;

import java.util.ArrayList;

import javax.annotation.Resource;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.ResponseBody;

import com.geppetto.braintree.dto.OrderDetail;
import com.geppetto.braintree.dto.Product;
import com.geppetto.braintree.services.OrderService;
import com.geppetto.braintree.services.ProductService;

/**
 * 
 * @author Geppetto Generated Code</br>
 * Date Created: </br>
 * @since  </br>
   build:   </p> 
 *
 * code was generated by the Geppetto System </br>
 * Gepppetto system Copyright - Geppetto LLC 2014 - 2015</br>
 * The generated code is free to use by anyone</p>
 *
 *
 *
*/
@Controller("ProductController")
@RequestMapping(value = "/product")
public class ProductController {
	
	private static final Logger LOG = LoggerFactory.getLogger(ProductController.class);
		
	private ProductService product_service;	
	
	private OrderService order_service;		
	
	public OrderService getOrder_service() {
		return order_service;
	}

	@Resource(name = "OrderService")
	public void setOrder_service(OrderService order_service) {
		this.order_service = order_service;
	}

	public ProductService getProduct_service() {
		return product_service;
	}

	@Resource(name = "ProductService")
	public void setProduct_service(ProductService product_service) {
		this.product_service = product_service;
	}


	@RequestMapping(value = "/getProducts", method = RequestMethod.GET, headers = "Accept=application/json")
	@ResponseBody
	public ArrayList<Product> getProducts() throws Exception {
		System.out.println("ProductController - getProducts");
		LOG.debug("ProductController - getProducts");
		ArrayList<Product> the_list = this.product_service.list_products();
		return the_list;
	}
	
	@RequestMapping(method = RequestMethod.POST, value = "/addToCart", headers = "Accept=application/json")
	@ResponseBody
	public OrderDetail addToCart(@RequestBody OrderDetail order_detail) throws Exception {
		System.out.println("adding product to cart! "+order_detail.getProduct_id());		
		
		return this.order_service.add_order(order_detail);
	}
	

}
