package com.geppetto.braintree.dao.support;

import java.sql.Types;

import javax.sql.DataSource;

import org.springframework.jdbc.core.SqlParameter;
import org.springframework.jdbc.object.SqlUpdate;

/**
 * 
 * @author Geppetto Generated Code</br>
 * Date Created: </br>
 * @since  </br>
   build:   </p> 
 *
 * code was generated by the Geppetto System </br>
 * Gepppetto system Copyright - Geppetto LLC 2014 - 2015</br>
 * The generated code is free to use by anyone</p>
 *
 *
 *
*/
public class InsertTransaction extends SqlUpdate {
	
	public static String SQL_INSERT_TRANSACTION = "";

	public InsertTransaction(DataSource dataSource) {
		super(dataSource, SQL_INSERT_TRANSACTION);
		super.declareParameter(new SqlParameter("transaction_id", Types.VARCHAR));
		super.declareParameter(new SqlParameter("transaction_date", Types.TIMESTAMP));
		super.declareParameter(new SqlParameter("transaction_type", Types.VARCHAR));
		super.declareParameter(new SqlParameter("status", Types.VARCHAR));
		super.declareParameter(new SqlParameter("customer_id", Types.BIGINT));
		super.declareParameter(new SqlParameter("credit_card", Types.VARCHAR));
		super.declareParameter(new SqlParameter("credit_card_type", Types.VARCHAR));
		super.declareParameter(new SqlParameter("amount", Types.DOUBLE));
		
		super.setGeneratedKeysColumnNames(new String[] { "id" });
		super.setReturnGeneratedKeys(true);

	}

}
