package com.geppetto.braintree.dao.support;

import java.sql.Types;

import javax.sql.DataSource;

import org.springframework.jdbc.core.SqlParameter;
import org.springframework.jdbc.object.SqlUpdate;

/**
 * 
 * @author Geppetto Generated Code</br>
 * Date Created: </br>
 * @since  </br>
   build:   </p> 
 *
 * code was generated by the Geppetto System </br>
 * Gepppetto system Copyright - Geppetto LLC 2014 - 2015</br>
 * The generated code is free to use by anyone</p>
 *
 *
 *
*/
public class InsertOrderDetail extends SqlUpdate {
	
	public static String SQL_INSERT_ORDER_DETAIL = "";

	public InsertOrderDetail(DataSource dataSource) {
		super(dataSource, SQL_INSERT_ORDER_DETAIL);
		super.declareParameter(new SqlParameter("order_id", Types.BIGINT));
		super.declareParameter(new SqlParameter("product_id", Types.BIGINT));
		super.declareParameter(new SqlParameter("quantity", Types.INTEGER));

		super.setGeneratedKeysColumnNames(new String[] { "id" });
		super.setReturnGeneratedKeys(true);
	}

}
