package com.geppetto.braintree.dao.support;

import java.sql.ResultSet;
import java.sql.SQLException;

import org.springframework.jdbc.core.RowMapper;

import com.geppetto.braintree.dto.OrderDetail;

/**
 * 
 * @author Geppetto Generated Code</br>
 * Date Created: </br>
 * @since  </br>
   build:   </p> 
 *
 * code was generated by the Geppetto System </br>
 * Gepppetto system Copyright - Geppetto LLC 2014 - 2015</br>
 * The generated code is free to use by anyone</p>
 *
 *
 *
*/
public class OrderDetailMapper implements RowMapper<OrderDetail> {

	@Override
	public OrderDetail mapRow(ResultSet rs, int rowNum) throws SQLException {
		
		OrderDetail dto = new OrderDetail();
		
		dto.setId(rs.getLong("ID"));
		dto.setOrder_id(rs.getLong("ORDER_ID"));
		dto.setProduct_id(rs.getLong("PRODUCT_ID"));
		dto.setQuantity(rs.getInt("QUANTITY"));		
		
		return dto;
	}

}
