package com.geppetto.braintree.dao.support;

import java.sql.ResultSet;
import java.sql.SQLException;

import org.springframework.jdbc.core.RowMapper;

import com.geppetto.braintree.dto.Customer;
import com.geppetto.braintree.dto.Order;

/**
 * 
 * @author Geppetto Generated Code</br>
 * Date Created: </br>
 * @since  </br>
   build:   </p> 
 *
 * code was generated by the Geppetto System </br>
 * Gepppetto system Copyright - Geppetto LLC 2014 - 2015</br>
 * The generated code is free to use by anyone</p>
 *
 *
 *
*/
public class OrderMapper implements RowMapper<Order> {

	@Override
	public Order mapRow(ResultSet rs, int rowNum) throws SQLException {
		
		Order dto = new Order();
		
		Customer customer = new Customer();
		customer.setId(rs.getLong("CUSTOMER_ID"));
		
		dto.setId(rs.getLong("ORDER_ID"));
		dto.setOrder_date(rs.getDate("ORDER_DATE"));	
		dto.setCustomer(customer);						
		
		return dto;		
	}

}
