package com.geppetto.braintree.dao.support;

import java.sql.ResultSet;
import java.sql.SQLException;

import org.springframework.jdbc.core.RowMapper;
import com.geppetto.braintree.dto.Product;

/**
 * 
 * @author Geppetto Generated Code</br>
 * Date Created: </br>
 * @since  </br>
   build:   </p> 
 *
 * code was generated by the Geppetto System </br>
 * Gepppetto system Copyright - Geppetto LLC 2014 - 2015</br>
 * The generated code is free to use by anyone</p>
 *
 *
 *
*/
public class ProductMapper implements RowMapper<Product> {

	@Override
	public Product mapRow(ResultSet rs, int rowNum) throws SQLException {

		Product dto = new Product();
		
		dto.setId(rs.getLong("PRODUCT_ID"));
		dto.setName(rs.getString("PRODUCT_NAME"));
		dto.setDescription(rs.getString("PRODUCT_DESCRIPTION"));
		dto.setPrice(rs.getDouble("PRODUCT_PRICE"));
		dto.setImage(rs.getString("PRODUCT_IMAGE"));		
		
		return dto;
	}

}
