package com.geppetto.braintree.interfaces.dao;

import com.geppetto.braintree.dto.Customer;

/**
 * 
 * @author Geppetto Generated Code</br>
 * Date Created: </br>
 * @since  </br>
   build:   </p> 
 *
 * code was generated by the Geppetto System </br>
 * Gepppetto system Copyright - Geppetto LLC 2014 - 2015</br>
 * The generated code is free to use by anyone</p>
 *
 *
 *
*/
public interface ICustomerDao {

	public Customer get_customer_by_id(long customer_id) throws Exception;
}
