package com.geppetto.braintree.interfaces.dao;

import java.util.ArrayList;

import com.geppetto.braintree.dto.Product;

/**
 * 
 * @author Geppetto Generated Code</br>
 * Date Created: </br>
 * @since  </br>
   build:   </p> 
 *
 * code was generated by the Geppetto System </br>
 * Gepppetto system Copyright - Geppetto LLC 2014 - 2015</br>
 * The generated code is free to use by anyone</p>
 *
 *
 *
*/
public interface IProductDao {
	
	public ArrayList<Product> get_products() throws Exception;
	
	public Product get_product_by_id(long id) throws Exception;

}
