package com.geppetto.braintree.interfaces.services;

import com.geppetto.braintree.dto.Order;
import com.geppetto.braintree.dto.OrderDetail;

/**
 * 
 * @author Geppetto Generated Code</br>
 * Date Created: </br>
 * @since  </br>
   build:   </p> 
 *
 * code was generated by the Geppetto System </br>
 * Gepppetto system Copyright - Geppetto LLC 2014 - 2015</br>
 * The generated code is free to use by anyone</p>
 *
 *
 *
*/
public interface IOrderService {
	
	public OrderDetail add_order(OrderDetail order) throws Exception;
	
	public Order get_order() throws Exception;
	
	public void proccess_order() throws Exception;
	
	public void remove_product(long product_id) throws Exception; 
	
	public void update_quantity(long product_id, int quantity) throws Exception;

}
