package com.geppetto.braintree.interfaces.services;

import com.geppetto.braintree.dto.Customer;
import com.geppetto.braintree.dto.Transaction;

/**
 * 
 * @author Geppetto Generated Code</br>
 * Date Created: </br>
 * @since  </br>
   build:   </p> 
 *
 * code was generated by the Geppetto System </br>
 * Gepppetto system Copyright - Geppetto LLC 2014 - 2015</br>
 * The generated code is free to use by anyone</p>
 *
 *
 *
*/
public interface ITransactionService {
	
	public Transaction add_transaction(com.braintreegateway.Transaction transaction, Customer customer) throws Exception;

}
